"""fix tables

Revision ID: 654918c0b4a2
Revises: 23dcd6020dd6
Create Date: 2025-03-16 22:50:09.747741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '654918c0b4a2'
down_revision = '23dcd6020dd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=120), nullable=False),
    sa.Column('hashPass', sa.VARCHAR(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###
